name: Lint Dockerfiles

on: [push, pull_request]

jobs:
  dockerlint:
    runs-on: ubuntu-latest
    name: Lint Dockerfiles
    
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile